DO
$$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM asset) THEN
        INSERT INTO asset (id, ticker, name, type, currency, exchange, created_at, updated_at)
        VALUES
            (uuid_generate_v4(), 'CSAN3', 'Cosan', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RAIZ4', 'Raízen', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AZUL4', 'Azul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'COGN3', 'Cogna', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BBAS3', 'Banco do Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PCAR3', 'Grupo Pão de Açúcar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MGLU3', 'Magazine Luiza', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ABEV3', 'Ambev', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PETR4', 'Petrobras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'STBP3', 'Santos Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BBDC4', 'Banco Bradesco', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'B3SA3', 'B3', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VAMO3', 'Grupo Vamos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RAIL3', 'Rumo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'POMO4', 'Marcopolo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ITUB4', 'Itaú Unibanco', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ITSA4', 'Itaúsa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BEEF3', 'Minerva', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'IFCM3', 'Infracommerce', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CVCB3', 'CVC', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ASAI3', 'Assaí', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CSMG3', 'COPASA', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BHIA3', 'Casas Bahia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BBDC3', 'Banco Bradesco', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ELET3', 'Eletrobras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ANIM3', 'Ânima Educação', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EQTL3', 'Equatorial Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CPLE6', 'Copel', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CMIG4', 'Cemig', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WEGE3', 'WEG', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VALE3', 'Vale', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BBSE3', 'BB Seguridade', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CSNA3', 'Siderúrgica Nacional', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PETR3', 'Petrobras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TIMS3', 'TIM', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRAV3', '3R Petroleum', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'USIM5', 'Usiminas', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LREN3', 'Lojas Renner', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BPAC11', 'Banco BTG Pactual', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PRIO3', 'PetroRio', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MOTV3', 'Motiva', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENEV3', 'Eneva', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CBAV3', 'CBA', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRFS3', 'BRF', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RDOR3', 'Rede D''Or', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VBBR3', 'Vibra Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RCSL4', 'Recrusul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GGBR4', 'Gerdau', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EMBR3', 'Embraer', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PETZ3', 'Petz', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RENT3', 'Localiza', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SRNA3', 'Serena Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MRVE3', 'MRV', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DIRR3', 'Direcional', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RADL3', 'RaiaDrogasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SIMH3', 'Simpar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GOAU4', 'Metalúrgica Gerdau', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'KLBN11', 'Klabin', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'NATU3', 'NATURA', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'UGPA3', 'Ultrapar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'JHSF3', 'JHSF', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'YDUQ3', 'YDUQS', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CXSE3', 'Caixa Seguridade', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AZTE3', 'AZT Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SANB11', 'Banco Santander', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'INTB3', 'Intelbras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DXCO3', 'Dexco', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CPLE3', 'Copel', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SUZB3', 'Suzano', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SBSP3', 'Sabesp', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MRFG3', 'Marfrig', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ECOR3', 'EcoRodovias', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALOS3', 'Allos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALPA4', 'Alpargatas', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENGI11', 'Energisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MOVI3', 'Movida', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CMIN3', 'CSN Mineração', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AMER3', 'Americanas', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VIVT3', 'Vivo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PGMN3', 'Pague Menos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'NEOE3', 'Neoenergia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LWSA3', 'Locaweb', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEAB3', 'C&A', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FLRY3', 'Fleury', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ONCO3', 'Oncoclínicas', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GMAT3', 'Grupo Mateus', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CYRE3', 'Cyrela', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PORT3', 'Wilson Sons', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HBSA3', 'Hidrovias do Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AZZA3', 'Arezzo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRAP4', 'Bradespar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AURE3', 'Auren Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HAPV3', 'Hapvida', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PSSA3', 'Porto Seguro', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MLAS3', 'Multilaser', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MULT3', 'Multiplan', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SLCE3', 'SLC Agrícola', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TOTS3', 'Totvs', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RAPT4', 'Randon', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'KLBN4', 'Klabin', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'QUAL3', 'Qualicorp', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MTRE3', 'Mitre Realty', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRKM5', 'Braskem', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'IGTI11', 'Iguatemi', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GRND3', 'Grendene', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LJQQ3', 'Lojas Quero-Quero', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VULC3', 'Vulcabras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ISAE4', 'ISA Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HYPE3', 'Hypera', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SBFG3', 'Grupo SBF', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TEND3', 'Construtora Tenda', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TAEE11', 'Taesa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SMFT3', 'Smart Fit', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RECV3', 'PetroRecôncavo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ODPV3', 'Odontoprev', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'OIBR3', 'Oi', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CAML3', 'Camil Alimentos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GGPS3', 'GPS', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HBOR3', 'Helbor', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CASH3', 'Méliuz', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CURY3', 'Cury', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VIVA3', 'Vivara', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'KEPL3', 'Kepler Weber', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SMTO3', 'São Martinho', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SAPR4', 'Sanepar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CPFE3', 'CPFL Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'POSI3', 'Positivo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PDGR3', 'PDG Realty', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SAPR11', 'Sanepar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MELK3', 'Melnick', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FESA4', 'Ferbasa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SYNE3', 'SYN', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VVEO3', 'Viveo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GUAR3', 'Guararapes', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ELET6', 'Eletrobras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LIGT3', 'Light', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'JALL3', 'Jalles Machado', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EGIE3', 'Engie', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DASA3', 'Dasa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRSR6', 'Banrisul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TUPY3', 'Tupy', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BPAN4', 'Banco Pan', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SEER3', 'Ser Educacional', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LAVV3', 'Lavvi Incorporadora', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MILS3', 'Mills', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'USIM3', 'Usiminas', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BMOB3', 'Bemobi', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PLPL3', 'Plano&Plano', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AZEV4', 'Azevedo & Travassos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RANI3', 'Irani', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EZTC3', 'EZTEC', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TTEN3', '3tentos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AZEV3', 'Azevedo & Travassos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENJU3', 'Enjoei', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ARML3', 'Armac', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MATD3', 'Mater Dei', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MYPK3', 'Iochpe-Maxion', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CSED3', 'Cruzeiro do Sul Educacional', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'IRBR3', 'IRB Brasil RE', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VTRU3', 'VITRUBREPCOM', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TFCO4', 'Track & Field', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'OPCT3', 'OceanPact', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'POMO3', 'Marcopolo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BMGB4', 'Banco BMG', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ITUB3', 'Itaú Unibanco', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SHUL4', 'Schulz', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MDNE3', 'Moura Dubeux', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PINE4', 'Banco Pine', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TOKY3', 'TOKY3', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'JSLG3', 'JSL', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PRNR3', 'Priner', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TASA4', 'Taurus', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ABCB4', 'Banco ABC Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AMBP3', 'Ambipar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'UNIP6', 'Unipar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WIZC3', 'Wiz Soluções', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TRIS3', 'Trisul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SAPR3', 'Sanepar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ORVR3', 'Orizon', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GFSA3', 'Gafisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RNEW4', 'Renova Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'KLBN3', 'Klabin', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SOJA3', 'Boa Safra Sementes', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LOGG3', 'LOG CP', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALUP11', 'Alupar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MDIA3', 'M. Dias Branco', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BLAU3', 'Blau Farmacêutica', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LEVE3', 'Mahle Metal Leve', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FRAS3', 'Fras-le', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FIQE3', 'Unifique', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PNVL3', 'Dimed', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HBRE3', 'HBR Realty', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AGRO3', 'BrasilAgro', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VLID3', 'Valid', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PFRM3', 'Profarma', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PMAM3', 'Paranapanema', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EVEN3', 'Even', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRST3', 'Brisanet', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRBI11', 'BR Partners', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TGMA3', 'Tegma', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ZAMP3', 'Zamp', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LPSB3', 'Lopes', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ESPA3', 'Espaçolaser', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PTBL3', 'Portobello', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ROMI3', 'Indústrias ROMI', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MEAL3', 'IMC Alimentação', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TAEE4', 'Taesa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RCSL3', 'Recrusul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DEXP3', 'Dexxos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALLD3', 'Allied', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALPK3', 'Estapar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRAP3', 'Bradespar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEBR6', 'CEB', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SANB4', 'Banco Santander', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CMIG3', 'Cemig', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AMAR3', 'Lojas Marisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LUPA3', 'Lupatech', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ETER3', 'Eternit', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VITT3', 'Vittia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AALR3', 'Alliança', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BSLI3', 'Banco de Brasília', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DESK3', 'Desktop', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'IGTI3', 'Iguatemi', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TAEE3', 'Taesa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RNEW3', 'Renova Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SANB3', 'Banco Santander', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CSUD3', 'CSU Cardsystem', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SEQL3', 'Sequoia Logística', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ITSA3', 'Itaúsa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FICT3', 'Fictor Alimentos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TELB4', 'Telebras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AERI3', 'Aeris Energy', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EUCA4', 'Eucatex', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DMVF3', 'D1000 Varejo Farma', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WHRL4', 'Whirlpool', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'UCAS3', 'Unicasa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TECN3', 'Technos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SHOW3', 'Time For Fun', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TRAD3', 'Traders Club', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LOGN3', 'Log-In', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TCSA3', 'Tecnisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VIVR3', 'Viver', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BMEB4', 'Banco Mercantil do Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEBR3', 'CEB', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LVTC3', 'WDC Networks', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AGXY3', 'AgroGalaxy', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WEST3', 'Westwing', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EALT4', 'Electro Aço Altona', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BSLI4', 'Banco de Brasília', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AMOB3', 'Automob', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'REAG3', 'REAG3', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GOAU3', 'Metalúrgica Gerdau', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PDTC3', 'Padtec', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GGBR3', 'Gerdau', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CAMB3', 'Cambuci', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LAND3', 'Terra Santa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TASA3', 'Taurus', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DOTZ3', 'Dotz', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'UNIP3', 'Unipar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BEES3', 'Banestes', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'VSTE3', 'LE LIS BLANC', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENGI3', 'Energisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'COCE5', 'Coelce', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BIOM3', 'Biomm', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AZEV11', 'Azevedo & Travassos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENGI4', 'Energisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BAZA3', 'Banco da Amazônia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BPAC3', 'Banco BTG Pactual', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRKM3', 'Braskem', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TPIS3', 'Triunfo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALUP4', 'Alupar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RAPT3', 'Randon', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CGRA4', 'Grazziotin', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEBR5', 'CEB', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TELB3', 'Telebras', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'INEP4', 'Inepar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALPA3', 'Alpargatas', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BEES4', 'Banestes', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'NGRD3', 'Neogrid', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DOHL4', 'Döhler', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'INEP3', 'Inepar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRSR3', 'Banrisul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HOOT4', 'Hotéis Othon', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HAGA4', 'Haga', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BPAC5', 'Banco BTG Pactual', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CLSC4', 'Celesc', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MGEL4', 'Mangels', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'JFEN3', 'João Fortes', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RSID3', 'Rossi Residencial', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FHER3', 'Fertilizantes Heringer', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CGRA3', 'Grazziotin', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RVEE3', 'REVEE S.A.', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PTNT4', 'Pettenati', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WLMM4', 'WLM', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MNPR3', 'Minupar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ALUP3', 'Alupar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BOBR4', 'Bombril', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'OFSA3', 'Ourofino Saúde Animal', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AVLL3', 'Alphaville', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BGIP3', 'Banese', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'OIBR4', 'Oi', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEDO4', 'Cedro Têxtil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EPAR3', 'Embpar Participações', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RPMG3', 'Refinaria de Manguinhos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WHRL3', 'Whirlpool', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CRPG5', 'Tronox Pigmentos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EALT3', 'Electro Aço Altona', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EQPA3', 'Equatorial Energia Pará', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PINE3', 'Banco Pine', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RDNI3', 'RNI', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'OSXB3', 'OSX Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SCAR3', 'São Carlos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MTSA4', 'Metisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'DEXP4', 'Dexxos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PTNT3', 'Pettenati', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ISAE3', 'ISA Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RNEW11', 'Renova Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BGIP4', 'Banese', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'NUTR3', 'Nutriplant', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CTSA4', 'Santanense', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'REDE3', 'Rede Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PPLA11', 'PPLA', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PATI4', 'Panatlântica', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PINE11', 'Banco Pine', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BNBR3', 'Banco do Nordeste', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ATED3', 'ATOM EDUCAÇÃO E EDITORA S.A.', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GEPA4', 'Rio Paranapanema Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EMAE4', 'EMAE', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SNSY5', 'Sansuy', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AMAR11', 'Lojas Marisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EKTR4', 'Elektro', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MWET4', 'Wetzel', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AFLT3', 'Afluente T', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BIOM11', 'Biomm', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RSUL4', 'Metalúrgica Riosulense', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEEB3', 'COELBA', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'NEXP3', 'Brasil Brokers', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CTKA4', 'Karsten', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HBTS5', 'Habitasul', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RPAD5', 'Alfa Holdings', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ESTR4', 'Estrela', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LUXM4', 'Trevisa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'TKNO4', 'Tekno', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BMEB3', 'Banco Mercantil do Brasil', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MSPA4', 'Melhoramentos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BMIN4', 'Banco Mercantil de Investimentos', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CPLE5', 'Copel', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEED3', 'CEEE D', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'NORD3', 'Nordon', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'RPAD3', 'Alfa Holdings', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GSHP3', 'General Shopping & Outlets', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BMKS3', 'Monark', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FIEI3', 'Fica', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BIED3', 'BIED3', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CGAS5', 'Comgás', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BALM4', 'Baumer', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EUCA3', 'Eucatex', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'UNIP5', 'Unipar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MAPT4', 'Cemepe', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CTSA3', 'Santanense', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CTKA3', 'Karsten', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CALI3', 'Adolpho Lindenberg', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BDLL3', 'Bardella', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BRKM6', 'Braskem', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENMT3', 'Energisa MT', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PATI3', 'Panatlântica', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'GEPA3', 'Rio Paranapanema Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CBEE3', 'Ampla Energia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HAGA3', 'Haga', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MNDL3', 'Mundial', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SOND5', 'Sondotécnica', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'FESA3', 'Ferbasa', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PEAB4', 'Participações Aliança da Bahia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EQMA3B', 'Equatorial Maranhão', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ADMF3', 'REAG TRUST S.A', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'ENMT4', 'Energisa MT', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'AHEB3', 'São Paulo Turismo', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'WLMM3', 'WLM', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PLAS3', 'Plascar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'LUPA11', 'LUPA11', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CALI11', 'CALI11', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CGAS3', 'Comgás', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MOAR3', 'Monteiro Aranha', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CEEB5', 'COELBA', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CCTY3', 'RDVC CITY', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'PEAB3', 'Participações Aliança da Bahia', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'HETA4', 'Hercules', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CLSC3', 'Celesc', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'IGTI4', 'Jereissati Participações', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'SOND6', 'Sondotécnica', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'COCE3', 'Coelce', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BALM3', 'Baumer', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'JOPA3', 'Josapar', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'EQPA5', 'Equatorial Energia Pará', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'MRSA3B', 'MRS Logística', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'BAUH4', 'Excelsior', 'STOCK', 'BRL', 'B3', now(), now()),
            (uuid_generate_v4(), 'CRPG3', 'Tronox Pigmentos', 'STOCK', 'BRL', 'B3', now(), now());
    END IF;
END $$;
